// <auto-generated />
using JokesAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JokesAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240303033211_AddUserUpvotes2")]
    partial class AddUserUpvotes2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JokesAPI.Models.Joke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Jokes");
                });

            modelBuilder.Entity("JokesAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JokesAPI.Models.UserUpvote", b =>
                {
                    b.Property<int>("UpvoterId")
                        .HasColumnType("int");

                    b.Property<int>("UpvotedUserId")
                        .HasColumnType("int");

                    b.HasKey("UpvoterId", "UpvotedUserId");

                    b.HasIndex("UpvotedUserId");

                    b.ToTable("UsersUpvote");
                });

            modelBuilder.Entity("JokesAPI.Models.Joke", b =>
                {
                    b.HasOne("JokesAPI.Models.User", "Author")
                        .WithMany("Jokes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("JokesAPI.Models.UserUpvote", b =>
                {
                    b.HasOne("JokesAPI.Models.User", "UpvotedUser")
                        .WithMany("UpvotedUsers")
                        .HasForeignKey("UpvotedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JokesAPI.Models.User", "Upvoter")
                        .WithMany("Upvoters")
                        .HasForeignKey("UpvoterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UpvotedUser");

                    b.Navigation("Upvoter");
                });

            modelBuilder.Entity("JokesAPI.Models.User", b =>
                {
                    b.Navigation("Jokes");

                    b.Navigation("UpvotedUsers");

                    b.Navigation("Upvoters");
                });
#pragma warning restore 612, 618
        }
    }
}
